name    'puppet-gitlab-redmine-common'
version '0.0.1'
source  'git://github.com/kleinmann/puppet_gitlab_common.git'
author  'Uwe Kleinmann'
license 'BSD'
summary 'Puppet module for common parts of GitLab and redmine'
description 'Puppet module for common parts of GitLab and redmine'
project_page 'https://github.com/kleinmann/puppet_gitlab_common'
dependency 'puppetlabs/stdlib', '>= 2.2.1'
